Jogo da velha (primeira versão)
franciscodonini/programacao pull request #1
Opened 2020-05-14 20:29 UTC by franciscodonini

- Placar de vitórias;
- Indicador de turno;
- Alerta de vitória com o player ganhador;
- Alerta de empate; 

| Jogo em execução |
| --- |
| <img src='https://user-images.githubusercontent.com/63026661/81982243-e2aac000-9607-11ea-8fc7-5142b527b9be.gif' width=450> |

2020-05-14 23:13 UTC, alandariva reviewed
A parte do html ou css não tenho muito o que comentar, eu parei a um bom tempo de mexer muito afundo com isso. Pra mim se está apresentando certo e não tem gambiarra ta ok.

Coloquei alguns comentários na parte do javascript. No mais ta bem legal, acho que talvez alguns nomes de variáveis da pra mudar, exemplo pGeral pode ser pontuacaoGeral, acredito que o pessoal não está tentando abreviar muito nomes de variáveis. Tem algumas coisas de formatação que não estão no mesmo padrão, tipo: `verificaVitoria ()` com espaço entre o nome e os parenteses.

2020-05-14 23:13 UTC, alandariva commented on jogoDaVelha.html
> +        elemento = document.getElementById (id);
É sempre bom utilizar let para inicializar as variáveis, olha o exemplo abaixo (no primeiro a saida é 100 e no segundo 500):

function geraVidaInicialInimigo() {
    vida = 100 // utiliza uma variável chamada pontuação que deveria ser local
    return vida
}

function resetaVidaInicialHeroi() {
    vida = 500
}

var vida = 0

resetaVidaInicialHeroi()
var vidaInimigo = geraVidaInicialInimigo()
alert(vida)

-------------------------

utilizando let:

function geraVidaInicialInimigo() {
    let vida = 100
    return vida
}

function resetaVidaInicialHeroi() {
    vida = 500
}

let vida = 0

resetaVidaInicialHeroi()
let vidaInimigo = geraVidaInicialInimigo()
alert(vida)

2020-05-14 23:13 UTC, alandariva commented on jogoDaVelha.html
> +        if (popUpVitoria.className == 'popUpVitoriaFechado') {
Está ok aqui, mas se tivesse mais condições que precisassem ser alinhadas, tipo:
if (a) {
   if (b) {
      if (c) {
     } ...
   }
}

seria melhor terminar a função ali mesmo com

if (popUpVitoria.className != 'popUpVitoriaFechado') {
     return;
}

2020-05-14 23:13 UTC, alandariva commented on jogoDaVelha.html
> +                if (clique == false) {
Alterar a ordem pra leitura

if (clique) {
....
} else {
 ....
}

2020-05-14 23:13 UTC, alandariva commented on jogoDaVelha.html
> +                }
me confundi um pouco aqui hehehehe.
seria melhor criar um verificaEmpate, ficaria mais legivel
```suggestion
                } else if (verificaEmpate()) {
                    exibeAvisoEmpate();
                }
```

2020-05-14 23:13 UTC, alandariva commented on jogoDaVelha.html
> +        return false
Não tem nada de errado aqui, só dependendo da quantidade de chaves que tu precise usar fique melhor usar variáveis para guardar o valor e ficar mais simples a condição. Abaixo coloquei dois outros modos de fazer a mesma coisa.

```suggestion
        var vitoria = [ [0,1,2],
                        [3,4,5],
                        [6,7,8],
                        [0,4,8],
                        [6,4,2],
                        [0,3,6],
                        [1,4,7],
                        [2,5,8] ]
        for ( var i = 0 ; i < vitoria.length ; i++) {
            let jogada1 = pGeral[vitoria[i][0]].textContent
            let jogada2 = pGeral[vitoria[i][1]].textContent
            let jogada3 = pGeral[vitoria[i][2]].textContent
            
            if (jogada1 == jogada2 &&
                jogada1 == jogada3 &&
                jogada1 != "") {
                return true
            }
        }
        return false
```

Ainda daria pra fazer assim, mas dai não sei se facilita ou dificulta:

```suggestion
        var vitoria = [ [0,1,2],
                        [3,4,5],
                        [6,7,8],
                        [0,4,8],
                        [6,4,2],
                        [0,3,6],
                        [1,4,7],
                        [2,5,8] ]
        for ( var i = 0 ; i < vitoria.length ; i++) {
            let jogada = vitoria[i].map((iVitoria) => pGeral[iVitoria].textContent);

            if (jogada[0] == jogada[1] &&
                jogada[0] == jogada[2] &&
                jogada[0] != "") {
                return true
            }
        }
        return false
```

2020-05-14 23:25 UTC, alandariva commented on jogoDaVelha.html
> +        return false
Mais uma coisa, eu gosto também de ver como os outros resolveram o problema pra aprender. Segue outros projetos de tic tac toe:

https://codepen.io/vasanthkay/pen/KVzYzG?editors=001 (só js)
https://github.com/mediaupstream/tic-tac-toe-js (usa jquery)

2020-05-15 01:31 UTC, doniniramos requested changes

2020-05-15 01:31 UTC, doniniramos commented on jogoDaVelha.html
> +        }
Essas linhas não precisam estar dentro do `for`
```
popUpVitoria.className = 'popUpVitoriaFechado' ;
popUpEmpate.className = 'popUpEmpateFechado' ;
```

2020-05-15 01:31 UTC, doniniramos commented on jogoDaVelha.html
> +                if (clique == false) {
NIT trocar `== false` por `!clique`

2020-05-15 01:31 UTC, doniniramos commented on jogoDaVelha.html
> +    </div>
Embora funcione, não acho que os popups façam parte do tabuleiro 👍

2020-05-15 01:31 UTC, doniniramos commented on jogoDaVelha.html
> +<style>
`font-family: 'Luckiest Guy', cursive;` Se repete ao longo do `style`, tu pode atribuir isso a tag `body` e deixar ela englobando as demais `tags`

Pode aproveitar isso pra implementar uma estrutura de html mais padrão, tipo essa:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<HTML>
   <HEAD>
      <TITLE>My first HTML document</TITLE>
   </HEAD>
   <BODY>
      <P>Hello world!
   </BODY>
</HTML>
```

2020-05-15 01:31 UTC, doniniramos commented on jogoDaVelha.html
> +        z-index: 100;
NIT definir a unidade `px`, `pt`, `em`, etc ao longo do `style`

2020-05-15 01:31 UTC, doniniramos commented on jogoDaVelha.html
> +    }
`popUpVitoriaAberto` e `popUpEmpateAberto ` são iguais, tu pode usar um só, `popUpAberto` por exemplo, o mesmo acontece com o `popUpVitoriaFechado`

2020-05-15 01:31 UTC, doniniramos commented on jogoDaVelha.html
> +        return false
Top esses exempos, o segundo é muito lindo 💯

2020-06-12 00:10 UTC, franciscodonini commented on jogoDaVelha.html
> +        return false
Valeu pelas sugestões Alan! Eu achei a primeira muito mais fácil de elaborar e ler.

2020-06-12 00:30 UTC, franciscodonini commented on jogoDaVelha.html
> +    </div>
Eles estão dentro do tabuleiro para poder centralizar ao abrirem no meio do tabuleiro.

2020-06-12 00:35 UTC, franciscodonini commented
Fiz algumas alterações, algumas decidi não fazer para poder avaliar minha evolução de acordo com o que consegui criar. Espero que tenha melhorado.

2020-06-12 00:35 UTC, merged